In [1]:
import tensorflow as tf
import numpy as np

In [2]:
node1 = tf.constant(3.0)
node2 = tf.constant(4.0)
sess = tf.Session()
sess.run(node1)

3.0

In [3]:
sess.run([node1,node2])

[3.0, 4.0]

In [4]:
sess.run(node1+node2)

7.0

In [5]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
node = a/b
sess.run(node, {a: [4,3], b: [2, 1]})

array([ 2.,  3.], dtype=float32)

In [6]:
sess.run(node, {a: 1, b:0})

inf

In [7]:
W = tf.Variable([2.], tf.float32)
b = tf.Variable([-1.], tf.float32)
x = tf.placeholder(tf.float32)
linear_model = x * W + b

In [8]:
linear_model

<tf.Tensor 'add_1:0' shape=<unknown> dtype=float32>

In [9]:
try: 
    sess.run(W)  
except:
    import sys
    print("sess.run(W) throws an error ...")
    print(sys.exc_info())

sess.run(W) throws an error ...
(<class 'tensorflow.python.framework.errors_impl.FailedPreconditionError'>, FailedPreconditionError(), <traceback object at 0x0000014582043AC8>)


### Must initialize variables before "running" the graph...

In [10]:
init = tf.global_variables_initializer()
sess.run(init)

In [11]:
sess.run(linear_model, {x:[1,2,3,4]})

array([ 1.,  3.,  5.,  7.], dtype=float32)

In [12]:
sess.run(W)

array([ 2.], dtype=float32)

In [13]:
sess.run(tf.assign(W,[1.]))

array([ 1.], dtype=float32)

In [14]:
sess.run(W)

array([ 1.], dtype=float32)

In [15]:
sess.run(linear_model, {x:[1,2,3,4]})

array([ 0.,  1.,  2.,  3.], dtype=float32)