In [24]:
import numpy as np
import tensorflow as tf

In [25]:
batch_size = 4
vocabulary_size = 10
embedding_size = 3

In [26]:
train_dataset = tf.placeholder(tf.int32, shape=[batch_size])
embeddings = tf.Variable(tf.random_uniform([vocabulary_size, embedding_size], -1.0, 1.0), name='W')
embed = tf.nn.embedding_lookup(embeddings, train_dataset)

In [27]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [32]:
sess.run(embeddings, {train_dataset: [1,1,1,1]})

array([[-0.77455139,  0.7781477 ,  0.09982991],
       [-0.23738837,  0.65014315,  0.33966303],
       [ 0.7795186 ,  0.65099335, -0.40258765],
       [ 0.22063327,  0.33806729, -0.39233494],
       [ 0.27529788,  0.64186621,  0.25571322],
       [-0.15469694, -0.70605254, -0.19627142],
       [ 0.06660748, -0.18626881,  0.3886044 ],
       [-0.82496405,  0.31851625,  0.28163433],
       [ 0.5667944 , -0.86580753, -0.43156743],
       [-0.59517646, -0.8930676 , -0.19159651]], dtype=float32)

In [36]:
sess.run(embed, {train_dataset: [1,2,1,0]})

array([[-0.23738837,  0.65014315,  0.33966303],
       [ 0.7795186 ,  0.65099335, -0.40258765],
       [-0.23738837,  0.65014315,  0.33966303],
       [-0.77455139,  0.7781477 ,  0.09982991]], dtype=float32)

In [40]:
norm = tf.sqrt(tf.reduce_sum(tf.square(embeddings), 1, keep_dims=True))
sess.run(norm)

array([[ 1.10245621],
       [ 0.77098012],
       [ 1.09248257],
       [ 0.56293446],
       [ 0.74375421],
       [ 0.7489751 ],
       [ 0.43605736],
       [ 0.92808193],
       [ 1.12121773],
       [ 1.09018993]], dtype=float32)

In [41]:
normalized_embeddings = embeddings / norm
norm1 = tf.sqrt(tf.reduce_sum(tf.square(normalized_embeddings), 1, keep_dims=True))
sess.run(norm1)

array([[ 0.99999994],
       [ 0.99999994],
       [ 1.        ],
       [ 0.99999994],
       [ 0.99999994],
       [ 1.        ],
       [ 0.99999988],
       [ 0.99999994],
       [ 0.99999994],
       [ 0.99999994]], dtype=float32)

In [51]:
similarity = tf.matmul(normalized_embeddings, tf.transpose(normalized_embeddings))
similarity

<tf.Tensor 'MatMul_6:0' shape=(10, 10) dtype=float32>